[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js specific settings for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"